> 날짜 : 2023.05.07

<br />

## 🚨 문제 상황

- 우선 새 Repository를 생성한 후, 로컬 폴더와 `git remote` 명렁어로 연결해주었다.

- 그 후 로컬 폴더(저장소)에서 윈격 저장소로 (main -> main) 기존 폴더에 있던 파일들을 커밋 후 push했더니 해당 오류가 발생했다.

  ```
   ! [rejected]        main -> main (fetch first)
  error: 레퍼런스를 'https://github.com/SangYoonLee1231/reddit-app-clone.git'에 푸시하는데 실패했습니다
  힌트: 리모트에 로컬에 없는 사항이 들어 있으므로 업데이트가
  힌트: 거부되었습니다. 이 상황은 보통 또 다른 저장소에서 같은
  힌트: 저장소로 푸시할 때 발생합니다.  푸시하기 전에
  힌트: ('git pull ...' 등 명령으로) 리모트 변경 사항을 먼저
  힌트: 포함해야 합니다.
  힌트: 자세한 정보는 'git push --help'의 "Note about fast-forwards' 부분을
  힌트: 참고하십시오.
  ```

<br /><br />

## 💡 문제 원인 및 해결 과정

### <strong>원인</strong>

- 원인은 잘 모르겠다.

- 에러 메세지에는 '리모트에 로컬에 없는 사항이 들어 있으므로'라고 하는데, 리모트(원격 저장소)는 폴더가 깨끗이 비어있었으니 말이다.

<br />

### <strong>해결</strong>

- push 시 `--force` 명령어를 붙어 강제로 푸쉬해주었다.

  ```
  git push origin main --force
  ```

<br /><br />
